set(genmobile_SETUP_PY_SETUP_MODULE "distutils.core")
set(genmobile_SETUP_PY_VERSION "0.4.3")
set(genmobile_SETUP_PY_SCRIPTS "scripts/genmobile_message_artifacts")
set(genmobile_SETUP_PY_PACKAGES "genmobile")
set(genmobile_SETUP_PY_PACKAGE_DIRS "src/genmobile")
set(genmobile_SETUP_PY_MODULES "")
set(genmobile_SETUP_PY_MODULE_DIRS "")